apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: node-red
  name: node-red
spec:
  type: NodePort
  ports:
  - name: "1880"
    port: 1880
    targetPort: 1880
    nodePort: 32537
  selector:
    io.kompose.service: node-red
status:
  loadBalancer: {}
